# Generated by Django 5.0.3 on 2024-05-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_user_credit_card_address_user_credit_card_address_2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credit_card_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="credit_card_type_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="credit_card_type_3",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
