# Generated by Django 5.0.3 on 2024-05-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_user_credit_card_type_user_credit_card_type_2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credit_card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Visa", "Visa"),
                    ("MasterCard", "MasterCard"),
                    ("American Express", "American Express"),
                    ("Discover", "Discover"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_type_2",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Visa", "Visa"),
                    ("MasterCard", "MasterCard"),
                    ("American Express", "American Express"),
                    ("Discover", "Discover"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_type_3",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Visa", "Visa"),
                    ("MasterCard", "MasterCard"),
                    ("American Express", "American Express"),
                    ("Discover", "Discover"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
