# Generated by Django 5.0.3 on 2024-05-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_alter_user_credit_card_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credit_card_address",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_city",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_cvv",
            field=models.CharField(blank=True, default="", max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_expiry",
            field=models.DateField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_number",
            field=models.CharField(blank=True, default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_state",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Visa", "Visa"),
                    ("MasterCard", "MasterCard"),
                    ("American Express", "American Express"),
                    ("Discover", "Discover"),
                ],
                default="",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="credit_card_zip",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
