# Generated by Django 4.2.10 on 2024-05-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_alter_user_credit_card_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
