# Generated by Django 4.2.10 on 2024-05-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_alter_user_credit_card_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='credit_card_expiry',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
